### ISSUE TITLE
Struggling to use Vike + Preact + TanStack Query

### ISSUE THREAD

**Issue by jasonhilldm** [brillout/vike-preact#2]
I am using your vike-preact example as a starting point and am trying to add a simple fetch of data using TanStack Query. I have added a new link in the page shell to to a new page at **/movies**. When I first click the link to show that new page, I get a 500 error "Cannot read properties of null (reading 'useContext')". A second click on the same Movies link loads the new page correctly though.

I have created a stackblitz project to demonstrate the problem: https://stackblitz.com/edit/vitejs-vite-ttuaz6

I'm not sure what I am doing wrong here. I did have to add a QueryClientProvider wrapper in the **+onRenderClient.jsx** so not sure if that is correct.

**Comment by brillout** [comment]
I ain't that familiar with Preact, so I'd suggest asking the Preact community instead.
